project_id            = ""
region                = "southamerica-east1"
bucket_location       = "US"
instance_machine_type = "n4-highcpu-2"
# instance_image        = "ubuntu-2404-noble-amd64-v20250709"
instance_image        = "ubuntu-2204-jammy-v20250722"
instance_zone         = "southamerica-east1-a"
